[package]
name = "rhai-bigint"
version = "0.1.9"
edition = "2021"
description = "Rhai plugin providing arbitrary-precision BigInt support"
license = "MIT"
repository = "https://github.com/rhaiscript/rhai-bigint"
authors = ["Serge Kovbasiuk <isserge@protonmail.com>"]
keywords = ["rhai", "scripting", "bigint", "math", "plugin"]
categories = ["api-bindings", "mathematics"]

[features]
default = []
sync = ["rhai/sync"]
only_i32 = ["rhai/only_i32"]
metadata = ["rhai/metadata"]
rand = ["dep:rand", "num-bigint/rand"]

[dependencies]
num-bigint = "0.4.5"
num-traits = "0.2.19"
rand = { version = "0.8.5", optional = true }
rhai = "1.25.1"
